using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CostNAGAPI.Migrations
{
    public partial class addModel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Costs",
                columns: table => new
                {
                    CostId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    plant = table.Column<string>(type: "character varying(5)", nullable: true),
                    item_spec = table.Column<string>(type: "character varying(20)", nullable: true),
                    issue_date = table.Column<string>(type: "character varying(10)", nullable: true),
                    section = table.Column<string>(type: "character varying(10)", nullable: true),
                    doc_no = table.Column<string>(type: "character varying(20)", nullable: true),
                    wr_no = table.Column<string>(type: "character varying(20)", nullable: true),
                    sales = table.Column<string>(type: "character varying(10)", nullable: true),
                    revision_no = table.Column<string>(type: "character varying(10)", nullable: true),
                    checked_date = table.Column<string>(type: "character varying(10)", nullable: true),
                    approved_by = table.Column<string>(type: "character varying(10)", nullable: true),
                    expired_by = table.Column<string>(type: "character varying(10)", nullable: true),
                    customer = table.Column<string>(type: "character varying(20)", nullable: true),
                    parts_code = table.Column<string>(type: "character varying(15)", nullable: true),
                    item = table.Column<string>(type: "character varying(10)", nullable: true),
                    product = table.Column<string>(type: "character varying(20)", nullable: true),
                    product_type = table.Column<string>(type: "character varying(10)", nullable: true),
                    size = table.Column<string>(type: "character varying(10)", nullable: true),
                    business_type = table.Column<string>(type: "character varying(20)", nullable: true),
                    qty_month = table.Column<int>(type: "integer", nullable: false),
                    exchange_rate = table.Column<double>(type: "double precision", nullable: false),
                    target_price_bht = table.Column<double>(type: "double precision", nullable: false),
                    target_price_export = table.Column<double>(type: "double precision", nullable: false),
                    production_qty_day = table.Column<int>(type: "integer", nullable: false),
                    working_day = table.Column<int>(type: "integer", nullable: false),
                    rubber_material_name = table.Column<string>(type: "character varying(10)", nullable: true),
                    rubber_database_price_current = table.Column<double>(type: "double precision", nullable: false),
                    rubber_database_price_new = table.Column<double>(type: "double precision", nullable: false),
                    rubber_price_kg = table.Column<double>(type: "double precision", nullable: false),
                    rubber_mixing_process_cost = table.Column<double>(type: "double precision", nullable: false),
                    rubber_weight_g = table.Column<double>(type: "double precision", nullable: false),
                    rubber_weight_kg = table.Column<double>(type: "double precision", nullable: false),
                    rubber_yield_rate = table.Column<double>(type: "double precision", nullable: false),
                    rubber_weight_kg_yieldrate = table.Column<double>(type: "double precision", nullable: false),
                    rubber_cost_sgd = table.Column<double>(type: "double precision", nullable: false),
                    rubber_percentage_target_price = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_name_1 = table.Column<string>(type: "character varying(30)", nullable: true),
                    material_inhouse_info_1 = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_inhouse_value_1 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_info_1b = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_inhouse_value_1b = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_cost_sgd_1 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_percentage_target_price_1 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_name_2 = table.Column<string>(type: "character varying(30)", nullable: true),
                    material_inhouse_info_2 = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_inhouse_value_2 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_info_2b = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_inhouse_value_2b = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_cost_sgd_2 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_percentage_target_price_2 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_name_3 = table.Column<string>(type: "character varying(30)", nullable: true),
                    material_inhouse_info_3 = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_inhouse_value_3 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_info_3b = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_inhouse_value_3b = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_cost_sgd_3 = table.Column<double>(type: "double precision", nullable: false),
                    material_inhouse_percentage_target_price_3 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_name_1 = table.Column<string>(type: "character varying(30)", nullable: true),
                    material_outside_info_1 = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_outside_value_1 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_info_1b = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_outside_value_1b = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_cost_sgd_1 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_percentage_target_price_1 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_name_2 = table.Column<string>(type: "character varying(30)", nullable: true),
                    material_outside_info_2 = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_outside_value_2 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_info_2b = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_outside_value_2b = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_cost_sgd_2 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_percentage_target_price_2 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_name_3 = table.Column<string>(type: "character varying(30)", nullable: true),
                    material_outside_info_3 = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_outside_value_3 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_info_3b = table.Column<string>(type: "character varying(50)", nullable: true),
                    material_outside_value_3b = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_cost_sgd_3 = table.Column<double>(type: "double precision", nullable: false),
                    material_outside_percentage_target_price_3 = table.Column<double>(type: "double precision", nullable: false),
                    direct_material_cost = table.Column<double>(type: "double precision", nullable: false),
                    direct_material_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    sub_material_percentage = table.Column<double>(type: "double precision", nullable: false),
                    sub_material_cost = table.Column<double>(type: "double precision", nullable: false),
                    sub_material_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    direct_process_cost = table.Column<double>(type: "double precision", nullable: false),
                    direct_process_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    total_direct_cost = table.Column<double>(type: "double precision", nullable: false),
                    total_direct_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    defective_percentage = table.Column<double>(type: "double precision", nullable: false),
                    defective_cost = table.Column<double>(type: "double precision", nullable: false),
                    defective_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    indirect_percentage = table.Column<double>(type: "double precision", nullable: false),
                    indirect_cost = table.Column<double>(type: "double precision", nullable: false),
                    indirect_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    packing_material_percentage = table.Column<double>(type: "double precision", nullable: false),
                    special_package_cost = table.Column<double>(type: "double precision", nullable: false),
                    packing_material_cost = table.Column<double>(type: "double precision", nullable: false),
                    packing_material_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    administration_percentage = table.Column<double>(type: "double precision", nullable: false),
                    administration_cost = table.Column<double>(type: "double precision", nullable: false),
                    administration_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    plant_retail_percentage = table.Column<double>(type: "double precision", nullable: false),
                    plant_retail_cost = table.Column<double>(type: "double precision", nullable: false),
                    plant_retail_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    moldjig_percentage = table.Column<double>(type: "double precision", nullable: false),
                    moldjig_cost = table.Column<double>(type: "double precision", nullable: false),
                    moldjig_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    die_percentage = table.Column<double>(type: "double precision", nullable: false),
                    die_cost = table.Column<double>(type: "double precision", nullable: false),
                    die_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    note = table.Column<string>(type: "character varying(200)", nullable: true),
                    net_included_tooling_cost = table.Column<double>(type: "double precision", nullable: false),
                    net_included_tooling_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    net_exclude_tooling_cost = table.Column<double>(type: "double precision", nullable: false),
                    net_exclude_tooling_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_1 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_1 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_1 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_1 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_1 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_1 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_1 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_1 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_2 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_2 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_2 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_2 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_2 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_2 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_2 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_2 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_3 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_3 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_3 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_3 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_3 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_3 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_3 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_3 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_4 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_4 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_4 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_4 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_4 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_4 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_4 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_4 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_5 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_5 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_5 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_5 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_5 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_5 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_5 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_5 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_6 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_6 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_6 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_6 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_6 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_6 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_6 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_6 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_7 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_7 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_7 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_7 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_7 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_7 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_7 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_7 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_8 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_8 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_8 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_8 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_8 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_8 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_8 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_8 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_9 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_9 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_9 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_9 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_9 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_9 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_9 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_9 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_10 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_10 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_10 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_10 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_10 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_10 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_10 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_10 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_11 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_11 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_11 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_11 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_11 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_11 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_11 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_11 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_12 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_12 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_12 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_12 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_12 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_12 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_12 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_12 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_13 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_13 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_13 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_13 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_13 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_13 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_13 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_13 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_14 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_14 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_14 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_14 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_14 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_14 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_14 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_14 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_description_15 = table.Column<string>(type: "character varying(50)", nullable: true),
                    tooling_list_type_15 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_source_15 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_qty_15 = table.Column<int>(type: "integer", nullable: false),
                    tooling_list_unit_15 = table.Column<string>(type: "character varying(10)", nullable: true),
                    tooling_list_price_15 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_jpy_15 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_amount_usd_15 = table.Column<double>(type: "double precision", nullable: false),
                    tooling_list_total_amount_usd = table.Column<double>(type: "double precision", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Costs", x => x.CostId);
                });

            migrationBuilder.CreateTable(
                name: "Processes",
                columns: table => new
                {
                    ProcessId = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    doc_no = table.Column<string>(type: "character varying(20)", nullable: true),
                    process_name = table.Column<string>(type: "character varying(20)", nullable: true),
                    working_day = table.Column<double>(type: "double precision", nullable: false),
                    working_time_day = table.Column<double>(type: "double precision", nullable: false),
                    working_time_month = table.Column<double>(type: "double precision", nullable: false),
                    shift = table.Column<double>(type: "double precision", nullable: false),
                    worker = table.Column<double>(type: "double precision", nullable: false),
                    direct_labour = table.Column<double>(type: "double precision", nullable: false),
                    total_labour_cost = table.Column<double>(type: "double precision", nullable: false),
                    machine_qty = table.Column<double>(type: "double precision", nullable: false),
                    area = table.Column<double>(type: "double precision", nullable: false),
                    special_material = table.Column<double>(type: "double precision", nullable: false),
                    plant_maintenance = table.Column<double>(type: "double precision", nullable: false),
                    plant_maintenance_unit = table.Column<double>(type: "double precision", nullable: false),
                    total_machine_cost = table.Column<double>(type: "double precision", nullable: false),
                    machine_usage_day = table.Column<double>(type: "double precision", nullable: false),
                    machine_cost_month = table.Column<double>(type: "double precision", nullable: false),
                    machine_cost_month_percentage = table.Column<double>(type: "double precision", nullable: false),
                    machine_cost_month_percentage_unit = table.Column<double>(type: "double precision", nullable: false),
                    consumption_kwh = table.Column<double>(type: "double precision", nullable: false),
                    consumption_unit = table.Column<double>(type: "double precision", nullable: false),
                    consumption_sgd = table.Column<double>(type: "double precision", nullable: false),
                    consumption_rate = table.Column<double>(type: "double precision", nullable: false),
                    utility_electric = table.Column<double>(type: "double precision", nullable: false),
                    machine_utility_cost = table.Column<double>(type: "double precision", nullable: false),
                    labour_electric_cost = table.Column<double>(type: "double precision", nullable: false),
                    charge = table.Column<double>(type: "double precision", nullable: false),
                    cycle_time = table.Column<double>(type: "double precision", nullable: false),
                    cycle_time_unit = table.Column<double>(type: "double precision", nullable: false),
                    time = table.Column<double>(type: "double precision", nullable: false),
                    capacity = table.Column<double>(type: "double precision", nullable: false),
                    time_g = table.Column<double>(type: "double precision", nullable: false),
                    efficiency = table.Column<double>(type: "double precision", nullable: false),
                    production_capacity = table.Column<double>(type: "double precision", nullable: false),
                    production_cycle_time = table.Column<double>(type: "double precision", nullable: false),
                    special_input = table.Column<double>(type: "double precision", nullable: false),
                    direct_process_cost = table.Column<double>(type: "double precision", nullable: false),
                    labour_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    machine_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    overhead_cost_percentage = table.Column<double>(type: "double precision", nullable: false),
                    total_cost_percentage = table.Column<double>(type: "double precision", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Processes", x => x.ProcessId);
                });

            migrationBuilder.CreateTable(
                name: "Costs_Processes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    CostId = table.Column<int>(type: "integer", nullable: false),
                    ProcessId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Costs_Processes", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Costs_Processes_Costs_CostId",
                        column: x => x.CostId,
                        principalTable: "Costs",
                        principalColumn: "CostId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Costs_Processes_Processes_ProcessId",
                        column: x => x.ProcessId,
                        principalTable: "Processes",
                        principalColumn: "ProcessId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Costs_Processes_CostId",
                table: "Costs_Processes",
                column: "CostId");

            migrationBuilder.CreateIndex(
                name: "IX_Costs_Processes_ProcessId",
                table: "Costs_Processes",
                column: "ProcessId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Costs_Processes");

            migrationBuilder.DropTable(
                name: "Costs");

            migrationBuilder.DropTable(
                name: "Processes");
        }
    }
}
